name: Flutter Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Flutter SDK
      uses: subosito/flutter-action@v1
      with:
        channel: stable
        version: 3.7.7
        packages: flutter,flutter_test,flutter_driver

    - name: Install dependencies
      run: flutter pub get

    - name: Run unit tests
      run: flutter test
