name: Flutter Test
on:
  push:
    branches:
      - "main"
      - "version/*"
      - "feature/*"

  workflow_dispatch:

jobs:
  build:
    name: Run unit tests
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'

      - name: Install dependencies and run tests
        run: |
          cd cryptochain
          flutter pub get
          flutter test
